### ISSUE TITLE
Support client-side basic auth

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/toot#10]
Using the Toot config, we should allow setting a client-side PW.  Having the client-side PW set should cause the Toot::HandlerService to automatically be wrapped in a `Rack::Auth::Basic` middleware.  It should also automatically inject basic auth params into the callback URL that it posts to the server.

The server should then treat 400 responses from the client as a reason to unsubscribe that URL, in case the auth params change we don't want to continue hitting an old URL.

**Comment by jpowell** [comment]
Isn’t this what toot-auth does?

--
Justin Powell

Sent from my phone

On Oct 14, 2019, at 8:36 AM, Gordon <notifications@github.com> wrote:

﻿

Using the Toot config, we should allow setting a client-side PW. Having the client-side PW set should cause the Toot::HandlerService to automatically be wrapped in a Rack::Auth::Basic middleware. It should also automatically inject basic auth params into the callback URL that it posts to the server.

The server should then treat 400 responses from the client as a reason to unsubscribe that URL, in case the auth params change we don't want to continue hitting an old URL.

**Comment by gburgett** [comment]
Not exactly.  toot-auth's most valuable function is as a collection of helpers for creating and storing credentials.  There's some minor configuration it does to wrap the Toot::HandlerService in a Rack::Auth::Basic, but it expects the server and client to have shared the same credentials and doesn't really provide a mechanism for doing that.

What I'm proposing is that when you set `Toot.config.client_password = ...` then that gets injected into the callback URL that's configured.  Example:

```rb
Toot.config do |c|
  c.callback_url = Rails.application.routes.url_helpers.engine_url
  c.client_password = 'super-secret'
end

RegistersSubscriptions.call
# POST https://toot-server.com/subscriptions
# {
#   "callback_url": "https://u:super-secret@www.toot-client.com/callbacks"
#   "channel": "..."
# }
```
