### ISSUE TITLE
Use Redis Sorted Set for auto-expiring webhooks

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/toot#12]
Webhook URLs can become stale.  Especially if we allow anonymous clients to send in a webhook (currently we don't), or have clients that change their auth params (again, not our use case just yet).

Rather than continuing to hit a stale webhook URL, we should by default store the webhook URL along with the timestamp that it was last successfully registered or contacted.  Then we can delete stale ones.

- [ ] Change all instances of using Redis Set to use Redis [Sorted Set](https://redis.io/topics/data-types#sorted-sets) where the score is the timestamp of the last successful access / registration
- [ ] Provide a migration path to update existing data store from Set to Sorted Set
- [ ] Define "stale" and provide a mechanism to expire stale webhooks

**Comment by jpowell** [comment]
obe
